### ISSUE TITLE
Unable to load more than one element of the FBX/OBJ/3DS file.

### ISSUE THREAD

**Issue by L34D3R** [GameInstitute/RuntimeMeshLoader#2]
I tried to load mesh (FBX/OBJ/3DS) file using the "load mesh" node of the plugin. I am able to load the first element of the object. 

I am creating the procedural mesh section by loading all the vertices, normal, triangles , UVs as shown in the below blueprint.
![blueprint](https://user-images.githubusercontent.com/13694300/28172620-b174d3ba-6809-11e7-815e-aacccca4cba7.JPG)

After loading the file my viewport look like this. There is missing element number 2. It also automatically rotate the object.

![viewport](https://user-images.githubusercontent.com/13694300/28172657-c36a3632-6809-11e7-897b-a99387c5fbb7.JPG)

![viewport2](https://user-images.githubusercontent.com/13694300/28172806-49415678-680a-11e7-8ffa-5c737b7c8db7.JPG)

Here is the original FBX file of the object.
![fbx](https://user-images.githubusercontent.com/13694300/28172678-d6535b52-6809-11e7-975f-6cda578bec17.JPG)

How do i load the missing element of the object ?

**Comment by GameInstitutes** [comment]
Thx, I will working on it

**Comment by L34D3R** [comment]
@GameInstitutes : Is there any update on this ?

**Comment by GameInstitutes** [comment]
I had finished read all mesh information except the sub tranformation.
Please wait the update.

**Comment by L34D3R** [comment]
@GameInstitutes : Thank you so much , let me know when the update is available.

**Comment by sebastiansopp** [comment]
Any Updates to this issue?

**Comment by GR90** [comment]
this plugin for which version of UE4

**Comment by arclee** [comment]
I do this fo multi mesh.
https://gist.github.com/arclee/c6280b73b5143bfd8475161ed18c0b21

**Comment by GameInstitute** [comment]
Thanks for @arclee 's solution.
Solved in [https://github.com/GameInstitute/RuntimeMeshLoader/commit/e6c017e4e13923b85fe4222fb538996734433d30](url)
