### ISSUE TITLE
Cant connect mesh info array to break mesh info node

### ISSUE THREAD

**Issue by Tim4135** [GameInstitute/RuntimeMeshLoader#5]
Hi,

I would like to use your plugin in unreal 4.17.2 .
It compiles but when i run the example blueprint it says i cant connect the output mesh info node to the break meshinfo node.
But i need to do that in order to get the useful info.
Can you please please fix it?

![afbeelding](https://user-images.githubusercontent.com/22937934/31916597-c49601ea-b853-11e7-8a94-1d5524a1a216.png)
(look at the break return data and break meshinfo nodes and the blue connection between them)

thanks

**Comment by Tim-Electronics** [comment]
edit:
soled it by taking the first index of the array and connect that to break mesh info.

**Comment by GameInstitute** [comment]
Follow the wiki
