### ISSUE TITLE
Why can't open the package exe?

### ISSUE THREAD

**Issue by a576435459** [GameInstitute/RuntimeMeshLoader#6]
I packed the project, but I couldn't open the package                 Why??????
  Please!Help

**Comment by AzSweldnRakAn** [comment]
Same problem here, can sb. help? Works perfectly in editor but packaged project crash/didn't start.

**Comment by a576435459** [comment]
如果你解决了也告诉我下吧。 Let me know if you solve it。 あなたが解決したら私に教えてください。네가 해결 한 다면 내게 말 해 줘.

**Comment by manuganu9** [comment]
I am facing the same problem.

**Comment by L34D3R** [comment]
Bump here, I'm also not able to open the packaged exe.

**Comment by Tim-Electronics** [comment]
You need to include the assimp dlls with your application for it to work.

**Comment by darkanimator** [comment]
Hi there, where in the application i should include the assimp dlls? and which one specifically? a step by step would be appreciated

**Comment by Tim4135** [comment]
they should be in the plugins folder in your project, then under thirdpart/assimp/bin/(your arch)/
replace your arch with the architecture you build it for, prob. x64.
There you got the assimp files, copy the dll over to the location of your game executable and it should work.

**Comment by a576435459** [comment]
According to your method, I still can't.

**Comment by darkanimator** [comment]
Yes same here, I've try copying the files everywhere and it's still not working, but looking at the crash report it seems like it comes from not able to find the plugin itself. I've made a fresh project and used the code provided by https://wiki.unrealengine.com/Assimp_for_Unreal and it works even after packaged (provided i put dll and lib files in the right place, all in the link). I'm using unreal 4.16.3

**Comment by Tim4135** [comment]
Strange, thought that would work.
You could try copying the dlls from the build folder also.

**Comment by a576435459** [comment]
What version are you using?

**Comment by darkanimator** [comment]
I'm using the latest code for this plugin with Unreal 4.16.3.  if i use the plugin the error from the crash log is "LogStreaming:Error: Couldn't find file for package /Script/RuntimeMeshLoader requested by async loading code. NameToLoad: /Script/RuntimeMeshLoader" no matter where i put the dlls. However if i use Assimp directly it say it's missing the dll. which then when i copy the dlls and libs to the right directly it works perfectly. so i guess for now i'll have to use assimp direct.

**Comment by a576435459** [comment]
Error: Assertion failed: Object [File:D:\Build\++UE4+Release-4.17+Compile\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\LinkerLoad.cpp] [Line: 3107]

while creating the package, i get these errors

**Comment by darkanimator** [comment]
Yes I got the same error when I use the plugin

**Comment by a576435459** [comment]
If you solve it Pleats tell me   
me too.

**Comment by GameInstitutes** [comment]
Copy assimp-vc140-mt.dll to your game's Binaries\Win32 folder

**Comment by GameInstitutes** [comment]
Copy assimp-vc140-mt.dll in ThirdParty/assimp/bin/x86 or x64 folder to your game's Binaries\Win32 or Win64 folder

**Comment by GR90** [comment]
The plugin   to which  version of UE4

**Comment by GameInstitute** [comment]
Follow the wiki https://github.com/GameInstitute/RuntimeMeshLoader/wiki
