### ISSUE TITLE
unavilable for 4.16.3

### ISSUE THREAD

**Issue by Kyridiculous2** [GameInstitute/RuntimeMeshLoader#7]
after i add the blueprint and hit the compile, the engine shut down immediately and the log said:
 symbol lookup error:  libUE4Editor-RuntimeMeshLoader.so: undefined symbol: _ZN6Assimp8ImporterC1Ev

**Comment by GameInstitute** [comment]
https://github.com/GameInstitute/RuntimeMeshLoader/tree/4.16.3
